// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Download']['Download'](arg1, arg2, arg3, arg4);
}

export function VideoList(arg1, arg2) {
  return window['go']['app']['Download']['VideoList'](arg1, arg2);
}
