// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';

export function Download(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<response.Reply>;

export function VideoList(arg1:string,arg2:boolean):Promise<response.Reply>;
