// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {login} from '../models';
import {response} from '../models';

export function Code(arg1:login.CodeDTO):Promise<response.Reply>;
