// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netcase} from '../models';
import {response} from '../models';

export function ParseInfo(arg1:Array<netcase.ParseInfoDTO>):Promise<response.Reply>;

export function Process(arg1:netcase.ProcessDTO):Promise<response.Reply>;
