// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseInfo(arg1) {
  return window['go']['app']['Netcase']['ParseInfo'](arg1);
}

export function Process(arg1) {
  return window['go']['app']['Netcase']['Process'](arg1);
}
